add_test([=[WORKS!test1.Insert]=]  D:/VisualStudio/ProgrammingProjects/algds2024/lab2/lab_2/lab_2/binaries/Debug/UnitTesting.exe [==[--gtest_filter=WORKS!test1.Insert]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WORKS!test1.Insert]=]  PROPERTIES WORKING_DIRECTORY D:/VisualStudio/ProgrammingProjects/algds2024/lab2/lab_2/lab_2/binaries SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[WORKS!test1.Find]=]  D:/VisualStudio/ProgrammingProjects/algds2024/lab2/lab_2/lab_2/binaries/Debug/UnitTesting.exe [==[--gtest_filter=WORKS!test1.Find]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WORKS!test1.Find]=]  PROPERTIES WORKING_DIRECTORY D:/VisualStudio/ProgrammingProjects/algds2024/lab2/lab_2/lab_2/binaries SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[WORKS!test1.Join]=]  D:/VisualStudio/ProgrammingProjects/algds2024/lab2/lab_2/lab_2/binaries/Debug/UnitTesting.exe [==[--gtest_filter=WORKS!test1.Join]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WORKS!test1.Join]=]  PROPERTIES WORKING_DIRECTORY D:/VisualStudio/ProgrammingProjects/algds2024/lab2/lab_2/lab_2/binaries SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[test2.Insert]=]  D:/VisualStudio/ProgrammingProjects/algds2024/lab2/lab_2/lab_2/binaries/Debug/UnitTesting.exe [==[--gtest_filter=test2.Insert]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[test2.Insert]=]  PROPERTIES WORKING_DIRECTORY D:/VisualStudio/ProgrammingProjects/algds2024/lab2/lab_2/lab_2/binaries SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[test2.Split]=]  D:/VisualStudio/ProgrammingProjects/algds2024/lab2/lab_2/lab_2/binaries/Debug/UnitTesting.exe [==[--gtest_filter=test2.Split]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[test2.Split]=]  PROPERTIES WORKING_DIRECTORY D:/VisualStudio/ProgrammingProjects/algds2024/lab2/lab_2/lab_2/binaries SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  UnitTesting_TESTS [==[WORKS!test1.Insert]==] [==[WORKS!test1.Find]==] [==[WORKS!test1.Join]==] test2.Insert test2.Split)
